# Generated by Django 4.2.7 on 2024-02-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
