# Generated by Django 4.2.7 on 2024-02-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
        ('users', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='files_manager.file'),
        ),
    ]
