# Generated by Django 4.2.7 on 2023-12-31 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_directories', '0002_alter_blocksdirectory_district_and_more'),
        ('projects', '0002_rename_ia_active_project_is_active'),
        ('users', '0007_userproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProjectBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_directories.blocksdirectory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects', to='users.user')),
            ],
            options={
                'db_table': 'user_project_block',
            },
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
