# Generated by Django 4.2.7 on 2023-12-26 09:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files_manager', '0005_alter_file_hash'),
        ('farmers', '0005_alter_farmer_category'),
        ('users', '0007_userproject'),
        ('local_directories', '0002_alter_blocksdirectory_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('beneficiary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(128)])),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficiary_added_by', to='users.user')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='farmers.farmer')),
                ('id_back_image', models.ForeignKey(db_column='id_back_image', on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficiary_id_back_image', to='files_manager.file')),
                ('id_front_image', models.ForeignKey(db_column='id_front_image', on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficiary_id_front_image', to='files_manager.file')),
                ('last_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficiary_last_edited_by', to='users.user')),
                ('profile_photo', models.ForeignKey(db_column='profile_photo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficiary_profile_photo', to='files_manager.file')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='local_directories.villagesdirectory')),
            ],
            options={
                'db_table': 'beneficiaries',
            },
        ),
    ]
