# Generated by Django 4.2.7 on 2024-01-15 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('local_directories', '0001_initial'),
        ('files_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.CharField(choices=[('PRIVATE', 'Private'), ('COMMUNITY', 'Community')], default='PRIVATE', max_length=20)),
                ('geo_trace', models.TextField()),
                ('area', models.FloatField()),
                ('khasra_number', models.CharField(max_length=100)),
                ('farm_workers', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='land_parcels_added_by', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_land_parcels', to='farmers.farmer')),
                ('last_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='land_parcels_last_edited_by', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='local_directories.villagesdirectory')),
            ],
            options={
                'db_table': 'land_parcels',
            },
        ),
        migrations.CreateModel(
            name='LandParcelPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcel_pictures', to='land_parcels.landparcel')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_manager.file')),
            ],
            options={
                'db_table': 'land_parcel_picture',
                'unique_together': {('land_parcel', 'picture')},
            },
        ),
    ]
