# Generated by Django 4.2.7 on 2024-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_parcels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landparcel',
            name='khasra_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
