# Generated by Django 4.2.7 on 2023-12-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0005_alter_file_hash'),
        ('land_parcels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landparcel',
            name='farm_picture',
        ),
        migrations.AlterField(
            model_name='landparcelpicture',
            name='land_parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcel_pictures', to='land_parcels.landparcel'),
        ),
        migrations.AlterUniqueTogether(
            name='landparcelpicture',
            unique_together={('land_parcel', 'picture')},
        ),
    ]
