"""
Django settings for projectngo project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xpbs42h2=l)6uudhk))78b(4u5bf3*ela8b*_!1e)ndixhgq)0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['haritika-org.ap-south-1.elasticbeanstalk.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'projects',
    'farmers',
    'land_parcels',
    'beneficiaries',
    'users',
    'local_directories',
    'files_manager',
    'carbon_sequestration',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'UNAUTHENTICATED_USER': 'users.models.AnonymousUser',
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ),
}

RSA_PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----
MIIEoQIBAAKCAQBCqoDMZ9wFGbhu08A//LWVVyUrOQ1Fol697L60bOeRCQ9ieiyV
I8kDjsIJ8TjqcUuwRMvUGtm3aUEmG8FMTjaoysN9jzSmYQ+zWQBUcJYDIIC9ETVP
DSwrldCI8tXaSZsgTgSvoRO+b+F/ccBtl10h09715UX3dF79W53FXjIhwiKeFRSm
+n7dNlgyXrpIl4Z5/G2ESzs8vsOnIUTRPajiHu4XkTu/OxHdnYcoZErAYId9Ntwl
bzagpWWMupvjoPYfvYIl5cQHgwqcW4equ8VKFJkPf81r4+fcthWigr1VbT+YVqCU
w9g6nFWcMwHFPXVMpt4/LFLm6oL6wvuSNiD9AgMBAAECggEAMLnoq/5ZfUzgVfjl
cp9lpULtwtrPTY8xCkZo2P0kgAiMOyErRtLCEJyeTKAIRqsKdErEZEI/0WPYH193
+CrOnq6dFj++bsFQtXie2hj0PFLcZdSXDzGEkFLO+dnr3sGf5YvAtxHXmYCy4/Cj
gjZ49smiFD5A1m4zI6F7/o8ruyooG8aglWjSIW+pxr8qBCzYMGZmraOmr0tBmb4x
24/5x/UaaNwMjacufWgly6q8RBAuL34BJeDopfdfBGNcdauYOhCS9mvzrMQwcMyB
LtzCyVIzex56T+iWa19mrMeODg0Fz+E/H5O3tnbT914fxXAgYY4EJRwNK27ZMKj+
ZjGi7QKBgQCFKWhMN2ufu9OvNMVSVT9n2u+2NItMULbZYU0JEjtoNVQ8qpv8YB6m
aNG+ejlhgRBDDN+chOwx9OYuuMlfB5FHp+aeYAI0eplNDljFI8TaqmHdKd00nRBO
uGGn8Uy73+/FxJ9nOUBh2JbGHlLIpiwLMb+Gp7qmSTeRB0YRYufKlwKBgQCAKein
YtYb5lN1qqT7suW6IUs3x2h5/N8NgLV6j0TAKNs0hdra20GokNhbrCkgYBwGYcVl
zAkyOLRHmuki8dV4qbgnea8nSfWtuutxSoENz4UA3T1IGcl6xobQmAsMdFMcphBc
0Bid1CBNJrLAqtFxiRNRLtqb9d1gQCV7FdcHiwKBgDJL65suK7aPyWsaMZXhoStn
JLfbrOnMauQ8vk441ruLuR+ZCYYQAEO2v9KEc/wCNdQ9npCOHHDaIb9wCI+eWh+I
qbEUboDH9fOHAbykwAwf4wsYbvcahDhXqHs4x1UHRpeapuLkWw8aMgjvFzG2olgw
GDmSTQvWB+j9qFeU1hxNAoGAaOhlHWbE1e+SD3YQOEt2ygXouQ7MEVaRCk95vYm6
gASxcevDenQQ6bcustNYkry5E+xCFZKPUIGj6B0Aiu8jivJ54C411lYu+PdRM9oF
i1V7jHqMaBFbn9kTj3l1ScuKIKA6Mo7QJ5j0m9J6bUUlzeajXkeZACKgA+JeC8OT
0QMCgYBqHO/9ngWXUgY5TUXXC9ZbeGHGD6Py/rLUmR54mEnTUU4XeDQUGU9kNNA7
m+OI7rNaivOL5wgnZOGOiXC7VakvBg0oC6IRzjfy8XheM4g0FOq9yiWzr3xgyXRR
2c7Wl8cxXIcmr0iz8ZJZLhY5SDdX+Jvqd4m+GbTndI2QbvKPCw==
-----END RSA PRIVATE KEY-----"""

RSA_PUBLIC_KEY = """----------BEGIN PUBLIC KEY-----
MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQBCqoDMZ9wFGbhu08A//LWV
VyUrOQ1Fol697L60bOeRCQ9ieiyVI8kDjsIJ8TjqcUuwRMvUGtm3aUEmG8FMTjao
ysN9jzSmYQ+zWQBUcJYDIIC9ETVPDSwrldCI8tXaSZsgTgSvoRO+b+F/ccBtl10h
09715UX3dF79W53FXjIhwiKeFRSm+n7dNlgyXrpIl4Z5/G2ESzs8vsOnIUTRPaji
Hu4XkTu/OxHdnYcoZErAYId9NtwlbzagpWWMupvjoPYfvYIl5cQHgwqcW4equ8VK
FJkPf81r4+fcthWigr1VbT+YVqCUw9g6nFWcMwHFPXVMpt4/LFLm6oL6wvuSNiD9
AgMBAAE=
-----END PUBLIC KEY-----"""

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ALGORITHM": "RS256",
    "SIGNING_KEY": RSA_PRIVATE_KEY,
    "VERIFYING_KEY": RSA_PUBLIC_KEY,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'haritika_org.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
    },
]

WSGI_APPLICATION = 'haritika_org.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        "NAME": "haritika_org",
        "USER": "haritikaorgadmin",
        "PASSWORD": "AgRt&125$JdTh^895",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "users.User"

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
