# Generated by Django 4.2.7 on 2023-11-21 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlocksDirectory',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='block code')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='block name')),
            ],
            options={
                'db_table': 'blocks_directory',
            },
        ),
        migrations.CreateModel(
            name='StatesDirectory',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='state code')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='state name')),
            ],
            options={
                'db_table': 'states_directory',
            },
        ),
        migrations.CreateModel(
            name='VillagesDirectory',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='village code')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='village name')),
                ('block_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_directories.blocksdirectory')),
            ],
            options={
                'db_table': 'villages_directory',
            },
        ),
        migrations.CreateModel(
            name='DistrictsDirectory',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='district code')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='district name')),
                ('state_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_directories.statesdirectory')),
            ],
            options={
                'db_table': 'districts_directory',
            },
        ),
        migrations.AddField(
            model_name='blocksdirectory',
            name='district_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_directories.districtsdirectory'),
        ),
    ]
