# Generated by Django 4.2.7 on 2023-12-03 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_directories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocksdirectory',
            name='district',
            field=models.ForeignKey(db_column='district_code', on_delete=django.db.models.deletion.CASCADE, to='local_directories.districtsdirectory'),
        ),
        migrations.AlterField(
            model_name='districtsdirectory',
            name='state',
            field=models.ForeignKey(db_column='state_code', on_delete=django.db.models.deletion.CASCADE, to='local_directories.statesdirectory'),
        ),
        migrations.AlterField(
            model_name='villagesdirectory',
            name='block',
            field=models.ForeignKey(db_column='block_code', on_delete=django.db.models.deletion.CASCADE, to='local_directories.blocksdirectory'),
        ),
    ]
