# Generated by Django 4.2.7 on 2023-11-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_directories', '0002_alter_blocksdirectory_district_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocksdirectory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='block name'),
        ),
        migrations.AlterField(
            model_name='districtsdirectory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='district name'),
        ),
        migrations.AlterField(
            model_name='villagesdirectory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='village name'),
        ),
    ]
