# Generated by Django 4.2.7 on 2024-01-15 06:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('local_directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(128)])),
                ('name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('SC', 'ScheduleCastes'), ('ST', 'ScheduleTribes'), ('OBC', 'OtherBackwardClass'), ('MINORITIES', 'Minorities')], default='GENERAL', max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('income_level', models.CharField(choices=[('<30k', '<30k'), ('30k-50k', '30k-50k'), ('50k-80k', '50k-80k'), ('>80k', '>80k')], max_length=20)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('id_back_image', models.ForeignKey(db_column='id_back_image', on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_back_image', to='files_manager.file')),
                ('id_front_image', models.ForeignKey(db_column='id_front_image', on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_front_image', to='files_manager.file')),
                ('last_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_edited_by', to=settings.AUTH_USER_MODEL)),
                ('profile_photo', models.ForeignKey(db_column='profile_photo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_photo', to='files_manager.file')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='local_directories.villagesdirectory')),
            ],
            options={
                'verbose_name': 'farmer',
                'verbose_name_plural': 'farmers',
                'db_table': 'farmers',
            },
        ),
    ]
