# Generated by Django 4.2.7 on 2023-11-23 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local_directories', '0003_alter_blocksdirectory_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(128)])),
                ('name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('SC', 'ScheduleCastes'), ('ST', 'ScheduleTribes'), ('OBC', 'OtherBackwardClass')], default='GENERAL', max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('id_front_image_s3_location', models.TextField()),
                ('id_back_image_s3_location', models.TextField()),
                ('income_level', models.CharField(choices=[('<30k', '<30k'), ('30k-50k', '30k-50k'), ('50k-80k', '50k-80k'), ('>80k', '>80k')], max_length=20)),
                ('added_by', models.CharField(editable=False, max_length=150)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited_by', models.CharField(max_length=150)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
                ('block_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='local_directories.blocksdirectory')),
                ('district_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='local_directories.districtsdirectory')),
                ('state_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='local_directories.statesdirectory')),
                ('village_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='local_directories.villagesdirectory')),
            ],
            options={
                'verbose_name': 'farmer',
                'verbose_name_plural': 'farmers',
                'db_table': 'farmers',
            },
        ),
    ]
