# Generated by Django 4.2.7 on 2023-11-16 17:35

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.CharField(max_length=128, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(128)])),
                ('name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('SC', 'ScheduleCastes'), ('ST', 'ScheduleTribes'), ('OBC', 'OtherBackwardClass')], default='GENERAL', max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('block', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('id_front_image_link', models.TextField()),
                ('id_back_image_link', models.TextField()),
                ('income_level', models.CharField(choices=[('<30k', '<30k'), ('30k-50k', '30k-50k'), ('50k-80k', '50k-80k'), ('>80k', '>80k')], max_length=20)),
            ],
            options={
                'verbose_name': 'farmer',
                'verbose_name_plural': 'farmers',
                'db_table': 'farmers',
            },
        ),
    ]
