# Generated by Django 4.2.7 on 2023-12-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='id_back_image_s3_location',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='id_front_image_s3_location',
        ),
        migrations.AddField(
            model_name='farmer',
            name='id_back_image',
            field=models.ForeignKey(db_column='id_back_image', default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_back_image', to='files_manager.file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='id_front_image',
            field=models.ForeignKey(db_column='id_front_image', default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_front_image', to='files_manager.file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='profile_photo',
            field=models.ForeignKey(db_column='profile_photo', default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_photo', to='files_manager.file'),
            preserve_default=False,
        ),
    ]
