# Generated by Django 4.2.7 on 2023-12-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_remove_farmer_id_back_image_s3_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='block',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='state',
        ),
    ]
