# Generated by Django 4.2.7 on 2023-12-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_alter_farmer_added_by_alter_farmer_last_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SC', 'ScheduleCastes'), ('ST', 'ScheduleTribes'), ('OBC', 'OtherBackwardClass'), ('MINORITIES', 'Minorities')], default='GENERAL', max_length=20),
        ),
    ]
