# Generated by Django 4.2.7 on 2023-12-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land_parcels', '0002_remove_landparcel_farm_picture_and_more'),
        ('files_manager', '0005_alter_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonSequestration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pits_target', models.IntegerField()),
                ('total_pits_dug', models.IntegerField(default=0)),
                ('total_pits_fertilized', models.IntegerField(default=0)),
                ('total_pits_planted', models.IntegerField(default=0)),
                ('agreement_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_document_type', to='files_manager.file')),
                ('carbon_waiver_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_waiver_document', to='files_manager.file')),
                ('gram_panchayat_resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gram_panchayat_resolution', to='files_manager.file')),
                ('land_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land_parcels.landparcel')),
            ],
            options={
                'db_table': 'carbon_sequestration',
            },
        ),
        migrations.CreateModel(
            name='CarbonSequestrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('MODEL_1_1', 'Model_1_1'), ('MODEL_1_2', 'Model_1_2'), ('MODEL_2_1', 'Model_2_1'), ('MODEL_2_2', 'Model_2_2'), ('MODEL_3', 'Model_3'), ('MODEL_4', 'Model_4')], max_length=20)),
                ('total_pits_target', models.IntegerField()),
                ('total_pits_dug', models.IntegerField(default=0)),
                ('total_pits_fertilized', models.IntegerField(default=0)),
                ('total_pits_planted', models.IntegerField(default=0)),
                ('carbon_sequestration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='carbon_sequestration.carbonsequestration')),
            ],
            options={
                'db_table': 'carbon_sequestration_models',
            },
        ),
    ]
