# Generated by Django 4.2.7 on 2023-12-26 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_sequestration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonsequestration',
            name='total_pits_dug',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carbonsequestration',
            name='total_pits_fertilized',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carbonsequestration',
            name='total_pits_planted',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carbonsequestration',
            name='total_pits_target',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
