# Generated by Django 4.2.7 on 2024-01-31 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_sequestration', '0002_remove_carbonsequestrationmodel_carbon_sequestration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbonsequestrationmodel',
            old_name='model',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='carbonsequestration',
            name='total_pits_target',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='carbonsequestrationprogress',
            name='total_pits_target',
            field=models.IntegerField(default=0),
        ),
    ]
