# Generated by Django 4.2.7 on 2024-02-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land_parcels', '0001_initial'),
        ('carbon_sequestration', '0003_rename_model_carbonsequestrationmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonsequestration',
            name='land_parcel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='land_parcels.landparcel'),
        ),
        migrations.AlterUniqueTogether(
            name='carbonsequestrationprogress',
            unique_together={('carbon_sequestration', 'model')},
        ),
    ]
