# Generated by Django 4.2.7 on 2024-03-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_sequestration', '0004_alter_carbonsequestration_land_parcel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonsequestration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
