# Generated by Django 4.2.7 on 2023-12-03 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('sha3_hash', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(128)])),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
