# Generated by Django 4.2.7 on 2024-01-15 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
                ('hash', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(64)])),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
