# Generated by Django 4.2.7 on 2023-12-03 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='sha3_hash',
        ),
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.CharField(default='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(128)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
