# Generated by Django 4.2.7 on 2023-12-04 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0002_remove_file_sha3_hash_file_hash_alter_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='added_by',
            field=models.CharField(default=1, editable=False, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='last_edited_by',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
