# Generated by Django 4.2.7 on 2023-12-04 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0003_file_added_by_file_added_on_file_last_edited_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='file',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='file',
            name='last_edited_by',
        ),
        migrations.RemoveField(
            model_name='file',
            name='last_edited_on',
        ),
    ]
