# Generated by Django 4.2.7 on 2023-12-04 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0004_remove_file_added_by_remove_file_added_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(64)]),
        ),
    ]
